env:
  AWS_DEFAULT_REGION: 'ap-southeast-2'

branches:
  only: 
    - master

before_install:
  - sudo apt-get update -qq
  - sudo pip install awscli

install:
  # Download and install the latest version of terraform
  - curl -o terraform.zip $(echo "https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')_linux_amd64.zip")
  - unzip terraform.zip && sudo mv terraform /usr/local/bin/terraform
  - terraform -v

script:
  - cd infrastructure
  - terraform init
  - terraform plan -input=false
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then terraform apply -auto-approve -input=false; fi'
