name: agdc
channels:
- conda-forge
- defaults
- nodefaults
dependencies:
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- cachetools
- cloudpickle >= 0.4.0 # pickle logger objects
- numpy
- singledispatch
- netcdf4
- psycopg2
- gdal >= 2.2.3
- rasterio >= 10.0a11
- xarray
- pathlib
- boto3 = 1.4.3
- cython # used by netcdf4 at compile only, but needed for compliance checker to load plugins
- pypeg2
